application: go-publy
version: 1
runtime: go
api_version: go1

handlers:
- url: /(user)
  script: _go_app
  login: required
  secure: optional

- url: /static/js
  static_dir: static/js

- url: /static/stylesheets
  static_dir: static/stylesheets

- url: /static/images
  static_dir: static/images 

- url: /.*
  script: _go_app
